{
 "title": "UPC Monitor Main",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "receiver_id",
    "label": "Downstream Receiver ID",
    "query": "SELECT receiver_id from upclive.downstream;"
   },
   {
    "name": "transmitter_id",
    "label": "Upstream Transmitter ID",
    "query": "SELECT transmitter_id from upclive.upstream;"
   }
  ]
 },
 "panels": [
  { "title": "Downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downstream SNR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  snr AS \"SNR ID 1\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 1 and 1 in ($receiver_id)\nGROUP BY time, snr\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  snr AS \"SNR ID 2\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 2 and 2 in ($receiver_id)\nGROUP BY time, snr\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  snr AS \"SNR ID 3\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 3 and 3 in ($receiver_id)\nGROUP BY time, snr\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  snr AS \"SNR ID 4\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 4 and 4 in ($receiver_id)\nGROUP BY time, snr\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  snr AS \"SNR ID 5\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 5 and 5 in ($receiver_id)\nGROUP BY time, snr\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  snr AS \"SNR ID 6\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 6 and 6 in ($receiver_id)\nGROUP BY time, snr\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  snr AS \"SNR ID 7\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 7 and 7 in ($receiver_id)\nGROUP BY time, snr\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  snr AS \"SNR ID 8\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 8 and 8 in ($receiver_id)\nGROUP BY time, snr\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power as \"Power ID 1\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 1 and 1 in ($receiver_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 2\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 2 and 2 in ($receiver_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 3\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 3 and 3 in ($receiver_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 4\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 4 and 4 in ($receiver_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 5\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 5 and 5 in ($receiver_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 6\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 6 and 6 in ($receiver_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 7\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 7 and 7 in ($receiver_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 8\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id = 8 and 8 in ($receiver_id)\nGROUP BY time, power\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Downstream Channels",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  receiver_id as \"Receiver ID\",\n  channel_id AS \"Channel ID\"\nFROM upclive.entry\nINNER JOIN upclive.downstream\nON upclive.downstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and receiver_id in ($receiver_id)\nGROUP BY time, receiver_id, channel_id\nORDER BY 1 DESC"
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Upstream Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 1\"\nFROM upclive.entry\nINNER JOIN upclive.upstream\nON upclive.upstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and transmitter_id = 1 and 1 in ($transmitter_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 2\"\nFROM upclive.entry\nINNER JOIN upclive.upstream\nON upclive.upstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and transmitter_id = 2 and 2 in ($transmitter_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 3\"\nFROM upclive.entry\nINNER JOIN upclive.upstream\nON upclive.upstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and transmitter_id = 3 and 3 in ($transmitter_id)\nGROUP BY time, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power AS \"Power ID 4\"\nFROM upclive.entry\nINNER JOIN upclive.upstream\nON upclive.upstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and transmitter_id = 4 and 4 in ($transmitter_id)\nGROUP BY time, power\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Upstream Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  transmitter_id as \"Receiver ID\",\n  channel_id AS \"Channel ID\"\nFROM upclive.entry\nINNER JOIN upclive.upstream\nON upclive.upstream.entry_id=upclive.entry.id\nWHERE\n  $__timeFilter(timestamp) and transmitter_id in ($transmitter_id)\nGROUP BY time, transmitter_id, channel_id\nORDER BY 1 DESC"
    }
   ]
  }
 ]
}